# Generated by Django 4.2.1 on 2023-06-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'жилье', 'verbose_name_plural': 'жилье'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='roomcount',
            options={'verbose_name': 'количество комнат', 'verbose_name_plural': 'количество комнат'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'тип жилья', 'verbose_name_plural': 'типы жилья'},
        ),
        migrations.RemoveField(
            model_name='housing',
            name='type',
        ),
        migrations.AddField(
            model_name='housing',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='housing.roomtype', verbose_name='тип жилья'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='count',
            field=models.IntegerField(verbose_name='количество комнат'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='тип жилья'),
        ),
    ]
